### ISSUE TITLE
🐛 [Bug] media file not parsing correctly

### ISSUE THREAD

**Issue by kkumar-gcc** [goravel/goravel#229]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.19.x

### Goravel Version (Goravel 版本)

1.12.5

### Describe The Problem (描述问题)

I am facing difficulties when trying to upload a media file using the `StoreMediaRequest` structure with validation. The storeMediaRequest object does not parse the data correctly.

```go
color.Redln("storeMediaRequest", storeMediaRequest)
//log output: storeMediaRequest {<nil> 0}
```

### Reproduction Code (复现代码或截图)

```go
//requests/store_media_request.go
...

type StoreMediaRequest struct {
	File      *multipart.FileHeader `form:"file" json:"file"`
	OwnerID   uint                  `form:"owner_id" json:"owner_id"`
	OwnerType string                `form:"owner_type" json:"owner_type"`
}

...

func (r *StoreMediaRequest) Rules(ctx http.Context) map[string]string {
	return map[string]string{
		"file": "required",
	}
}

... 
```
```go
//controllers/media_controller.go
....

func (r *MediaController) Store(ctx http.Context) {
	var storeMediaRequest requests.StoreMediaRequest
	errors, err := ctx.Request().ValidateRequest(&storeMediaRequest)
	if err != nil || errors != nil {
		helpers.ErrorResponse(ctx, http.StatusUnprocessableEntity, errors.All())
		return
	}
	color.Redln("storeMediaRequest", storeMediaRequest)

        ...
}
```

**Comment by hwbrzzl** [comment]
Thanks for your feedback, I found the root reason, and I'll create a PR for it, if not rush, we can release this fix to 1.13.0, It will take about a month.

**Comment by kkumar-gcc** [comment]
> Thanks for your feedback, I found the root reason, and I'll create a PR for it, if not rush, we can release this fix to 1.13.0, It will take about a month.

Sure, we can release it in v1.13.0.

**Comment by kkumar-gcc** [comment]
I think it still doesn't support multiple file upload. For example
```go
type StoreMediaRequest struct {
	Files     []*multipart.FileHeader `form:"files" json:"files"`
	OwnerID   uint                    `form:"owner_id" json:"owner_id"`
	OwnerType string                  `form:"owner_type" json:"owner_type"`
}
```
I am getting below error 
```go
2023/08/07 10:49:56 http: panic serving 127.0.0.1:60418: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x1ec55e0, 0x3eb2ac0})
	/usr/local/go/src/runtime/panic.go:890 +0x262
goravel/app/http/controllers.(*MediaController).Store(0x18?, {0x25f9c60, 0xc0005a81f8})
	/home/krish/goravel/gonga-goravel/app/http/controllers/media_controller.go:24 +0x74
github.com/goravel/framework/route.handlerToGinHandler.func1(0xc0001a2300)
	/home/krish/goravel/framework/route/utils.go:31 +0x86
github.com/gin-gonic/gin.(*Context).Next(...)
	/home/krish/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/goravel/framework/http.(*GinRequest).Next(0xc0005a81c8?)
	/home/krish/goravel/framework/http/gin_request.go:156 +0x31
github.com/goravel/framework/http.GinResponseMiddleware.func1({0x25f9c60?, 0xc0005a81c8})
	/home/krish/goravel/framework/http/gin_response.go:118 +0x17b
github.com/goravel/framework/route.middlewareToGinHandler.func1(0xc0001a2300)
	/home/krish/goravel/framework/route/utils.go:37 +0x86
github.com/gin-gonic/gin.(*Context).Next(...)
	/home/krish/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/goravel/framework/http.(*GinRequest).Next(0xc0005a80d8?)
	/home/krish/goravel/framework/http/gin_request.go:156 +0x31
github.com/goravel/framework/http/middleware.Cors.func1({0x25f9c60?, 0xc0005a80d8?})
	/home/krish/goravel/framework/http/middleware/cors.go:33 +0x459
github.com/goravel/framework/route.middlewareToGinHandler.func1(0xc0001a2300)
	/home/krish/goravel/framework/route/utils.go:37 +0x86
github.com/gin-gonic/gin.(*Context).Next(...)
	/home/krish/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0001a2300)
	/home/krish/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 +0xe7
github.com/gin-gonic/gin.(*Context).Next(...)
	/home/krish/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000484d00, 0xc0001a2300)
	/home/krish/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x671
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000484d00, {0x25f1868?, 0xc000acc000}, 0xc0001a2100)
	/home/krish/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
net/http.AllowQuerySemicolons.func1({0x25f1868, 0xc000acc000}, 0xc0001a2100)
	/usr/local/go/src/net/http/server.go:2974 +0x223
net/http.HandlerFunc.ServeHTTP(0x0?, {0x25f1868?, 0xc000acc000?}, 0x702674?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
net/http.serverHandler.ServeHTTP({0x25eb6a8?}, {0x25f1868, 0xc000acc000}, 0xc0001a2100)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0003da640, {0x25f3030, 0xc000cea840})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db
```

**Comment by hwbrzzl** [comment]
I think this error is caused by your own code, not the framework. But I found there is a problem when `Files     []*multipart.FileHeader`(`Files *multipart.FileHeader` is ok), waiting for feedback from the third package.

**Comment by kkumar-gcc** [comment]
Yeah, error is because of my code(I am trying to access property of files which is `nil`). But files shouldn't be `nil`.

**Comment by hwbrzzl** [comment]
Verified in https://github.com/gookit/validate@master, waiting for a new version.

<img width="920" alt="Image" src="https://github.com/user-attachments/assets/b0365fba-9e5a-4322-b6eb-62e19037ec2f" />
