### ISSUE TITLE
🐛 [Bug] Panic when running vendor:publish

### ISSUE THREAD

**Issue by vendion** [goravel/goravel#337]
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.21.x

### Goravel Version (Goravel 版本)

1.13.5

### Describe The Problem (描述问题)

After creating a package with `go run . artisan make:package openweather` when I try to publish the package with `go run . artisan vendor:publish -e -p ./packages/openweather` I get the following error:

```
panic: no vendor found

goroutine 1 [running]:
github.com/goravel/framework/console.(*Application).Run(0xc00012f910, {0xc000114180?, 0xc000af9170?, 0x3?}, 0x1)
        /home/vendion/go/pkg/mod/github.com/goravel/framework@v1.13.5/console/application.go:74 +0x2d4
github.com/goravel/framework/foundation.(*Application).bootArtisan(0x40b28b?)
        /home/vendion/go/pkg/mod/github.com/goravel/framework@v1.13.5/foundation/application.go:118 +0x47
github.com/goravel/framework/foundation.(*Application).Boot(0xc0000272c0)
        /home/vendion/go/pkg/mod/github.com/goravel/framework@v1.13.5/foundation/application.go:55 +0x105
goravel/bootstrap.Boot(...)
        /home/vendion/projects/temp-monitor/bootstrap/app.go:13
main.main()
        /home/vendion/projects/temp-monitor/main.go:11 +0x23
exit status 2
```

What is confusing is the package does exist on my filesystem and if I manually copy the config file from _packages/openweather/config/openweather.go_ to _config_ everything works just fine.

**Comment by vendion** [comment]
Also as a workaround for this issue, dealing with the config file was obvious, but what about when the package defines a new console command. Is there a way I can manually make that work?

**Comment by hwbrzzl** [comment]
If you want to run `go run . artisan vendor:publish -e -p ./packages/openweather`, you need to add the logic like below:

```
func (receiver *ServiceProvider) Boot(app foundation.Application) {
	app.Publishes("./packages/openweather", map[string]string{
		"config/cors.go": app.ConfigPath("cors.go"),
	})
}
```

**Comment by vendion** [comment]
@hwbrzzl I do have that set and I'm still getting that panic

```go
package openweather

import (
        "goravel/packages/openweather/commands"

        "github.com/goravel/framework/contracts/console"
        "github.com/goravel/framework/contracts/foundation"
)

const Binding = "openweather"

var App foundation.Application

type ServiceProvider struct{}

func (receiver *ServiceProvider) Register(app foundation.Application) {
        App = app

        app.Bind(Binding, func(app foundation.Application) (any, error) {
                return NewOpenweather(app.MakeConfig()), nil
        })
}

func (receiver *ServiceProvider) Boot(app foundation.Application) {
        app.Publishes("goravel/packages/openweather", map[string]string{
                "config/openweather.go": app.ConfigPath("openweather.go"),
        })
        app.Commands([]console.Command{
                commands.NewWeatherForecast(),
        })
}
```

**Comment by hwbrzzl** [comment]
Do you register your provider to `config/app.go`?

**Comment by vendion** [comment]
Yeap, did that before trying to run publish as well

```go

		// Autoload service providers
		//
		// The service providers listed here will be automatically loaded on the
		// request to your application. Feel free to add your own services to
		// this array to grant expanded functionality to your applications.
		"providers": []foundation.ServiceProvider{
			&log.ServiceProvider{},
			&console.ServiceProvider{},
			&database.ServiceProvider{},
			&cache.ServiceProvider{},
			&http.ServiceProvider{},
			&route.ServiceProvider{},
			&schedule.ServiceProvider{},
			&event.ServiceProvider{},
			&queue.ServiceProvider{},
			&grpc.ServiceProvider{},
			&mail.ServiceProvider{},
			&auth.ServiceProvider{},
			&hash.ServiceProvider{},
			&crypt.ServiceProvider{},
			&filesystem.ServiceProvider{},
			&validation.ServiceProvider{},
			&testing.ServiceProvider{},
			&providers.AppServiceProvider{},
			&providers.AuthServiceProvider{},
			&providers.RouteServiceProvider{},
			&providers.GrpcServiceProvider{},
			&providers.ConsoleServiceProvider{},
			&providers.QueueServiceProvider{},
			&providers.EventServiceProvider{},
			&providers.ValidationServiceProvider{},
			&providers.DatabaseServiceProvider{},
			&gin.ServiceProvider{},
			&openweather.ServiceProvider{},
		},
```

**Comment by hwbrzzl** [comment]
I tested it locally, please check your code using the following image:

<img width="1920" alt="image" src="https://github.com/goravel/goravel/assets/24771476/a319e4a5-355f-43e1-8897-5d906259cca7">

**Comment by vendion** [comment]
I tried creating a new package like you have above and go the same result:

```
vendion on Heimdall temp-monitor on  f-rewrite [!?⇡] via  v1.21.5 via  Node.js v20.8.1 took 39s
✗ go run . artisan make:package sms
Package created successfully: packages/sms

vendion on Heimdall temp-monitor on  f-rewrite [!?⇡] via  v1.21.5 via  Node.js v20.8.1 took 2s
➜ ls
app/        COPYING    go.sum    node_modules/  public/     routes/             tempmonitor.db
bootstrap/  database/  main.go   package.json   README.md   storage/            tests/
config/     go.mod     Makefile  packages/      resources/  tailwind.config.js  yarn.lock

vendion on Heimdall temp-monitor on  f-rewrite [!?⇡] via  v1.21.5 via  Node.js v20.8.1 took 51ms
➜ ls packages
openweather/  sms/

vendion on Heimdall temp-monitor on  f-rewrite [!?⇡] via  v1.21.5 via  Node.js v20.8.1 took 11s
➜ tree packages/sms
packages/sms
├── config
│   └── sms.go
├── contracts
│   └── sms.go
├── facades
│   └── sms.go
├── README.md
├── service_provider.go
└── sms.go

4 directories, 6 files

vendion on Heimdall temp-monitor on  f-rewrite [!?⇡] via  v1.21.5 via  Node.js v20.8.1 took 61ms
➜ nvim packages/sms/service_provider.go

vendion on Heimdall temp-monitor on  f-rewrite [!?⇡] via  v1.21.5 via  Node.js v20.8.1 took 1m34s
➜ nvim config/app.go

vendion on Heimdall temp-monitor on  f-rewrite [!?⇡] via  v1.21.5 via  Node.js v20.8.1 took 24s
➜ go run . artisan vendor:publish -e -p ./packages/sms
panic: no vendor found

goroutine 1 [running]:
github.com/goravel/framework/console.(*Application).Run(0xc000127620, {0xc0000401e0?, 0xc000b6c870?, 0x3?}, 0x1)
	/home/vendion/go/pkg/mod/github.com/goravel/framework@v1.13.5/console/application.go:74 +0x2d4
github.com/goravel/framework/foundation.(*Application).bootArtisan(0x40b28b?)
	/home/vendion/go/pkg/mod/github.com/goravel/framework@v1.13.5/foundation/application.go:118 +0x47
github.com/goravel/framework/foundation.(*Application).Boot(0xc000a5a900)
	/home/vendion/go/pkg/mod/github.com/goravel/framework@v1.13.5/foundation/application.go:55 +0x105
goravel/bootstrap.Boot(...)
	/home/vendion/projects/temp-monitor/bootstrap/app.go:13
main.main()
	/home/vendion/projects/temp-monitor/main.go:11 +0x23
exit status 2
```

If it will help, my source code (minus the `sms` packgae) is available at https://git.sr.ht/~vendion/temp-monitor/tree/f-rewrite if you want to check over it.

**Comment by hwbrzzl** [comment]
Should be `./packages/openweather`

<img width="640" alt="image" src="https://github.com/goravel/goravel/assets/24771476/4b5ffd7d-2de6-4fa9-9e0a-c4adf25d6391">

**Comment by vendion** [comment]
Good catch, thanks for the help.
